package gui;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import entities.Customer;
import entities.Home;
import entities.Hotel;
import entities.Property;
import entities.Reservation;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import entities.CustomerNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;


public class CreateReservation extends javax.swing.JFrame {

    DefaultListModel lm;
    private Property p1;
    private Customer c1;
    private List<Customer> customers = new ArrayList<>();
    private Customer custTracker;
    private List<Property> properties = Property.getProperties();
    private Property propTracker;
    private Reservation resTracker;
    private List<Reservation> reservations = new ArrayList<>();
    //int propertyIndex = 0;
    private List<Property> displayedProps = new ArrayList<>();
    private List<Property> filteredProps = new ArrayList<>();
    
    public CreateReservation() {
        initComponents();
        lm = new DefaultListModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCustomer = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tbxCustomerID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tbxFirstName = new javax.swing.JTextField();
        tbxLastName = new javax.swing.JTextField();
        tbxPhoneNumber = new javax.swing.JTextField();
        btnSearchCustomer = new javax.swing.JButton();
        panelPropertySearch = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tbxCheckIn = new javax.swing.JTextField();
        tbxCheckOut = new javax.swing.JTextField();
        panelAmenities = new javax.swing.JPanel();
        cbxSpa = new javax.swing.JCheckBox();
        cbxPool = new javax.swing.JCheckBox();
        cbxHighFloor = new javax.swing.JCheckBox();
        cbxPets = new javax.swing.JCheckBox();
        tbxCity = new javax.swing.JTextField();
        btnSearchProperties = new javax.swing.JButton();
        comboPropertyType = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        panelReservation = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listProperties = new javax.swing.JList<>();
        btnReserve = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        panelCustomer.setBorder(javax.swing.BorderFactory.createTitledBorder("Customer Search"));

        jLabel1.setText("Customer ID");

        jLabel2.setText("First Name");

        jLabel3.setText("Last Name");

        jLabel4.setText("Phone Number");

        btnSearchCustomer.setText("Search");
        btnSearchCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchCustomerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCustomerLayout = new javax.swing.GroupLayout(panelCustomer);
        panelCustomer.setLayout(panelCustomerLayout);
        panelCustomerLayout.setHorizontalGroup(
            panelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCustomerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelCustomerLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tbxFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelCustomerLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tbxCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSearchCustomer)
                    .addGroup(panelCustomerLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tbxLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tbxPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelCustomerLayout.setVerticalGroup(
            panelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustomerLayout.createSequentialGroup()
                .addGroup(panelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tbxCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchCustomer))
                .addGap(18, 18, 18)
                .addGroup(panelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tbxFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(tbxLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(tbxPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        panelPropertySearch.setBorder(javax.swing.BorderFactory.createTitledBorder("Property Search"));

        jLabel5.setText("Check-in");

        jLabel6.setText("Check-out");

        jLabel7.setText("City");

        panelAmenities.setBorder(javax.swing.BorderFactory.createTitledBorder("Amenities (optional)"));

        cbxSpa.setText("Spa");

        cbxPool.setText("Pool");
        cbxPool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxPoolActionPerformed(evt);
            }
        });

        cbxHighFloor.setText("High Floor");

        cbxPets.setText("Pet(s) Allowed");

        javax.swing.GroupLayout panelAmenitiesLayout = new javax.swing.GroupLayout(panelAmenities);
        panelAmenities.setLayout(panelAmenitiesLayout);
        panelAmenitiesLayout.setHorizontalGroup(
            panelAmenitiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAmenitiesLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panelAmenitiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxSpa)
                    .addComponent(cbxPool))
                .addGap(38, 38, 38)
                .addGroup(panelAmenitiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxHighFloor)
                    .addComponent(cbxPets))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelAmenitiesLayout.setVerticalGroup(
            panelAmenitiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAmenitiesLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panelAmenitiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxPool)
                    .addComponent(cbxHighFloor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelAmenitiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxPets)
                    .addComponent(cbxSpa))
                .addGap(68, 68, 68))
        );

        btnSearchProperties.setText("Search Properties");
        btnSearchProperties.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchPropertiesActionPerformed(evt);
            }
        });

        comboPropertyType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Any", "Condo", "House", "Hotel" }));

        jLabel8.setText("Property Type");

        javax.swing.GroupLayout panelPropertySearchLayout = new javax.swing.GroupLayout(panelPropertySearch);
        panelPropertySearch.setLayout(panelPropertySearchLayout);
        panelPropertySearchLayout.setHorizontalGroup(
            panelPropertySearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPropertySearchLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelPropertySearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPropertySearchLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tbxCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(jLabel7))
                    .addGroup(panelPropertySearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(tbxCity, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelPropertySearchLayout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tbxCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(53, 53, 53)
                            .addComponent(jLabel8)
                            .addGap(18, 18, 18)
                            .addComponent(comboPropertyType, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(101, 101, 101)
                .addComponent(panelAmenities, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(btnSearchProperties)
                .addGap(42, 42, 42))
        );
        panelPropertySearchLayout.setVerticalGroup(
            panelPropertySearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPropertySearchLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelPropertySearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPropertySearchLayout.createSequentialGroup()
                        .addGroup(panelPropertySearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPropertySearchLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(panelPropertySearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(tbxCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tbxCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(29, 29, 29)
                                .addGroup(panelPropertySearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(tbxCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboPropertyType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)))
                            .addComponent(panelAmenities, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPropertySearchLayout.createSequentialGroup()
                        .addComponent(btnSearchProperties)
                        .addGap(47, 47, 47))))
        );

        panelReservation.setBorder(javax.swing.BorderFactory.createTitledBorder("Reservation"));

        listProperties.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(listProperties);

        btnReserve.setText("Make Reservation");
        btnReserve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReserveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelReservationLayout = new javax.swing.GroupLayout(panelReservation);
        panelReservation.setLayout(panelReservationLayout);
        panelReservationLayout.setHorizontalGroup(
            panelReservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReservationLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 977, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnReserve))
        );
        panelReservationLayout.setVerticalGroup(
            panelReservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelReservationLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelReservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelReservationLayout.createSequentialGroup()
                        .addComponent(btnReserve)
                        .addGap(88, 88, 88)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelReservation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelPropertySearch, javax.swing.GroupLayout.PREFERRED_SIZE, 951, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(panelCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(panelPropertySearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(panelReservation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchCustomerActionPerformed
        
        
        String idSearch = tbxCustomerID.getText();
        
        
        try {
            //Iterates through all customers, searching based off of customerID
            custTracker = Customer.getCustomer(idSearch);
                String msg = "The customer is " + custTracker.getFname() + " " + custTracker.getLname() + "?";
                int confirm = JOptionPane.showConfirmDialog(this, msg, "Confirm", JOptionPane.YES_NO_OPTION);
                
                if (confirm == JOptionPane.YES_OPTION) {    //If user selects yes, the customer is correct
                    tbxCustomerID.setText(String.valueOf(custTracker.getCustomerID()));
                    tbxFirstName.setText(custTracker.getFname());
                    tbxLastName.setText(custTracker.getLname());
                    tbxPhoneNumber.setText(custTracker.getPhone());
                    tbxCustomerID.setEditable(false);
                    tbxFirstName.setEditable(false);
                    tbxLastName.setEditable(false);
                    tbxPhoneNumber.setEditable(false);
                    btnSearchProperties.setEnabled(true);
                    btnReserve.setEnabled(true);
                    
                    tbxCheckIn.setEditable(true);
                    tbxCheckIn.setEditable(true);
                    tbxCity.setEditable(true);
                }
                
                
            }
 
        catch (CustomerNotFoundException ex) {
            String error = "Customer not found. Please enter a valid CustomerID.";
            JOptionPane.showMessageDialog(this, error, "Customer not found", JOptionPane.ERROR_MESSAGE);
        }

        
    }//GEN-LAST:event_btnSearchCustomerActionPerformed

    private void btnSearchPropertiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchPropertiesActionPerformed
          
        lm.clear();    //Clears list, useful if button action performed multiple times
        boolean dateFormatValid = false;     //check for daete format -> true if able to be parsed from string
        
        try {
            LocalDate.parse(tbxCheckIn.getText());       //Throws exception if unable to parse
            LocalDate.parse(tbxCheckOut.getText()); 
            dateFormatValid = true;
        }
        catch (Exception e) {
            String error = "Please enter the date in YYYY-MM-DD format.";
            JOptionPane.showMessageDialog(this, error, "Date Format Error", JOptionPane.ERROR_MESSAGE);
        }
        
        if (dateFormatValid) {    //Assigning checkIn and checkOut if date format was determined to be valid
            LocalDate checkIn = LocalDate.parse(tbxCheckIn.getText());
            LocalDate checkOut = LocalDate.parse(tbxCheckOut.getText());
            if (checkIn.isAfter(checkOut)) {
                String warn = "The Check-In date must come before the Check-Out date.";
                JOptionPane.showMessageDialog(this, warn, "Date Error", JOptionPane.ERROR_MESSAGE);
            }
            else if (checkIn.isBefore(checkOut)) {
                int count = 0;
                if (cbxPool.isSelected() || cbxSpa.isSelected() || cbxHighFloor.isSelected() || cbxPets.isSelected()) {
                    count ++;
                }
                for (Property p : properties) {
                    if (p.checkAvailability(checkIn, checkOut) 
                            && p.getCity().equals(tbxCity.getText())) {
                        if ( count >= 1 && ((cbxPool.isSelected() && p.getAmenities().contains("Pool")) 
                                ||(cbxSpa.isSelected() && p.getAmenities().contains("Spa"))
                                ||(cbxHighFloor.isSelected() && p.getAmenities().contains("High Floor"))
                                        ||(cbxPets.isSelected() && p.getAmenities().contains("Pets Allowed")))) {
                           lm.addElement(p.toString());
                           displayedProps.add(p); 
                        }
                        else if (count == 0) {
                            lm.addElement(p.toString());
                            displayedProps.add(p);
                        }
                   }
               } 
                listProperties.setModel(lm);
            }
        }       
 
        if (displayedProps.isEmpty()) {
            String empty = "No available properties found.";
            JOptionPane.showMessageDialog(this, empty, "No Properties Found", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnSearchPropertiesActionPerformed

    private void btnReserveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReserveActionPerformed
        
        if (listProperties.getSelectedIndex() <= -1) {    //Nothing selected from list
            String error = "Please select a property to reserve.";
            JOptionPane.showMessageDialog(this, error, "Reservation Failed", JOptionPane.ERROR_MESSAGE);
        }
        
        else if (listProperties.getSelectedIndex() > -1) {    //Something selected from list
            String msg = "Are you sure you want to reserve this property?";
            int confirm = JOptionPane.showConfirmDialog(this, msg, "Confirm Reservation", JOptionPane.YES_NO_OPTION);
        
            if (confirm == JOptionPane.YES_OPTION) {    //If user confirms that they would like to reserve the selected property
                LocalDate checkIn = LocalDate.parse(tbxCheckIn.getText());
                LocalDate checkOut = LocalDate.parse(tbxCheckOut.getText());
                
                propTracker = displayedProps.get(listProperties.getSelectedIndex());
               
                resTracker = new Reservation(checkIn, checkOut, propTracker, custTracker);    //Creates new reservation with tracked customer and property data
                reservations.add(resTracker);
                String confirmation = "Reservation Confirmed. Reservation No. " + resTracker.getReservationID();
                JOptionPane.showMessageDialog(this, confirmation, "Reservation Confirmed", JOptionPane.INFORMATION_MESSAGE);
                resTracker.Persist();
                lm.removeElementAt(listProperties.getSelectedIndex());
                panelPropertySearch.setEnabled(false);
                btnSearchProperties.setEnabled(false);
                btnReserve.setEnabled(false);
            }
        }
    }//GEN-LAST:event_btnReserveActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        //used to instantiate all customers, properties, and an exisitng reservation as a test case
        //will update to import properties, maybe customer data via file i/o
        //p1 = new Home("1", 2, 12, 300, "555 Main St", "32060", "Miami", "FL", "Description", "King", "No amenities", 420.69);
        //c1 = new Customer("1", "Ryan", "Merritt", "123 SW 1st St", "ryan@gmail.com", "555-555-5555");
        //Property p2 = new Hotel("2", 2, 13, 350, "1406 Ave", "32608", "Miami", "FL", "Desc goes here", "Queen", "Issa hotel", 987.32);
        //customers.add(c1);
        //properties.add(p1);
        //properties.add(p2);
        //Customer c2 = new Customer("2", "Becky", "Messcher", "456 Main St", "becky@gmail.com", "229-563-2019");
        //customers.add(c2);
        //Reservation r1 = new Reservation(LocalDate.parse("2020-01-01"), LocalDate.parse("2020-01-06"), p2, c2);
        //reservations.add(r1);
        
        
        tbxFirstName.setEditable(false);
        tbxLastName.setEditable(false);
        tbxPhoneNumber.setEditable(false);
        btnSearchProperties.setEnabled(false);
        btnReserve.setEnabled(false);
        tbxCheckIn.setEditable(false);
        tbxCheckIn.setEditable(false);
        tbxCity.setEditable(false);
        
        
        
    }//GEN-LAST:event_formWindowOpened

    private void cbxPoolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxPoolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxPoolActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateReservation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReserve;
    private javax.swing.JButton btnSearchCustomer;
    private javax.swing.JButton btnSearchProperties;
    private javax.swing.JCheckBox cbxHighFloor;
    private javax.swing.JCheckBox cbxPets;
    private javax.swing.JCheckBox cbxPool;
    private javax.swing.JCheckBox cbxSpa;
    private javax.swing.JComboBox<String> comboPropertyType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listProperties;
    private javax.swing.JPanel panelAmenities;
    private javax.swing.JPanel panelCustomer;
    private javax.swing.JPanel panelPropertySearch;
    private javax.swing.JPanel panelReservation;
    private javax.swing.JTextField tbxCheckIn;
    private javax.swing.JTextField tbxCheckOut;
    private javax.swing.JTextField tbxCity;
    private javax.swing.JTextField tbxCustomerID;
    private javax.swing.JTextField tbxFirstName;
    private javax.swing.JTextField tbxLastName;
    private javax.swing.JTextField tbxPhoneNumber;
    // End of variables declaration//GEN-END:variables
}
